[build]
  command   = "hugo --gc --minify"
  publish   = "public"

[context.production.environment]
  HUGO_BASEURL = "https://heidegrillmelle.netlify.app"

[dev]
  command = "hugo server -D"
  port    = 1313