[build]
  command   = "hugo --gc --minify -D"
  publish   = "public"
  environment = { HUGO_VERSION = "0.123.7", HUGO_ENABLEGITINFO = "true" }

[context.production.environment]
  HUGO_ENV = "production"
