[build]
  command   = "hugo --gc --minify"
  publish   = "public"

[build.environment]
  # pick the Hugo version you’ve been testing locally
  HUGO_VERSION = "0.123.7"
  # optional, but good for extended-image features:
  HUGO_BUILDMODE = "extended"
